spring:
  batch:
    initialize-schema: always
  main:
    allow-circular-references: true

acquisition-server:
  url: sftp://localhost:22
  username: my_username
  password: my_password
  cases-directory: ./cases
  label: my_sftp_server

case-server:
  url: http://127.0.0.1/

liquibase:
  change-log: classpath:db/changelog/db.changelog-master.yaml

database:
  url: jdbc:postgresql://localhost:5432/import_history
  username: postgres
  password: postgres
  driverClassName: org.postgresql.Driver
