acquisition-server:
  url: sftp://localhost:22
  username: my_username
  password: my_password
  cases-directory: ./cases
  label: my_sftp_server

cassandra:
  contact-points: localhost
  port: 9042
  datacenter: datacenter1

case-server:
  url: http://127.0.0.1/
